### ISSUE TITLE
Toys Guix Channel Search

### ISSUE THREAD

**Issue by jgarte** [fishinthecalculator/mobilizon-reshare-guix#3]
Hi fellow Guixer,

Would you be interested in joining our Guix channel search engine?

https://toys.whereis.みんな/

If so, send a patch here adding your channel:

https://git.sr.ht/~whereiseveryone/toys#join

**Comment by fishinthecalculator** [comment]
I'm [moving the channel](https://git.sr.ht/~fishinthecalculator/mobilizon-reshare-guix) over to sr.ht. I'll be happy to add the channel once it'll be completely moved. Thank you!

**Comment by fishinthecalculator** [comment]
I just sent a patch :rocket:
